### ISSUE TITLE
How to call the picoTTS service?

### ISSUE THREAD

**Issue by RidaAyed** [Poeschl/ha-picoTTS_remote#4]
The addon is up and running (hassio docker). However, I only see `tts.clear_cache` in *Developer tools > Services*

Any hint on how to actually use pico as service in homeassistant?

configuration.yml
```
tts:
  - platform: picotts_remote
    host: 192.168.178.38
    port: 59126
```

The addon log
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[23:45:07] INFO: Start PicoTTS webserver
Start server on port 59126...****
```

**Comment by Poeschl** [comment]
Have you also installed the custom component?

**Comment by RidaAyed** [comment]
Thank your for answering that fast Poeschl.

Yes. I chose the second installation method "Manual" and downloaded the folder:

`root@raspberrypi:~# tree /usr/share/hassio/homeassistant/custom_components/picotts_remote/`

```
/usr/share/hassio/homeassistant/custom_components/picotts_remote/                        
├── __init__.py
├── manifest.json
├── __pycache__
│   ├── __init__.cpython-37.pyc
│   ├── __init__.cpython-38.pyc
│   ├── tts.cpython-37.pyc
│   └── tts.cpython-38.pyc
└── tts.py

1 directory, 7 files
```

**Comment by Poeschl** [comment]
The `custom_components` folder needs to be in your configuration folder. That might solve your issue. When no ``tts.*speak`` is available the component is not loaded by Home Assistant

The folder structure should be like that:
```
...../config                    
├── custom_components/picotts_remote/
...
├── automations.yaml
└── configuration.yaml
```

**Comment by RidaAyed** [comment]
Created `config` and copied `custom_components` into it, restarted hass. No changes:

Grepping log for `pico` returns:

```
2020-08-01 23:42:15 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for picotts_remote which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.     
                                                     
2020-08-01 23:42:16 ERROR (MainThread) [homeassistant.components.tts] Error setting up platform: picotts_remote
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 142, in async_setup_platform
    provider = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: get_engine() takes 2 positional arguments but 3 were given


```

**Comment by Poeschl** [comment]
I will look into reproducing it

**Comment by RidaAyed** [comment]
Works

1. Deleted `custom_components`
1. Created `custom_components`
1. Cloned this repository and moved its folder `picotts_remote` to `custom_components`

Thank you
