### ISSUE TITLE
error when calling picotts service

### ISSUE THREAD

**Issue by ebaschiera** [Poeschl/ha-picoTTS_remote#5]
Hi,
on Home Assistant 0.115.2 running on Raspberry 4 I am getting the following error when calling picotts service:

```
Logger: homeassistant.components.websocket_api.http.connection.547602550496
Source: components/tts/__init__.py:470
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 17:50:01 (1 occurrences)
Last logged: 17:50:01

'en-US' not a Frame instance
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 167, in async_say_handle
    url = await tts.async_get_url(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 340, in async_get_url
    filename = await self.async_get_tts_audio(
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 367, in async_get_tts_audio
    data = self.write_tags(filename, data, provider, message, language, options)
  File "/usr/src/homeassistant/homeassistant/components/tts/__init__.py", line 470, in write_tags
    tts_file["artist"] = artist
  File "/usr/local/lib/python3.8/site-packages/mutagen/_file.py", line 74, in __setitem__
    self.tags[key] = value
  File "/usr/local/lib/python3.8/site-packages/mutagen/id3/_tags.py", line 339, in __setitem__
    raise TypeError("%r not a Frame instance" % tag)
TypeError: 'en-US' not a Frame instance
```

I installed the supervisor addon from here: https://github.com/Poeschl/Hassio-Addons
...then this custom component via HACS.

I am calling the service like this:

service: ``tts.picotts_remote_say``
data: 
```
message: hi!
entity_id: media_player.google_home
```

Am I doing something wrong?

Thanks!

**Comment by Poeschl** [comment]
At the first look everything seems good. Can you also post your component config?
I will try to look into it the next days.

**Comment by marecabo** [comment]
I can confirm this behavior on 115.3 x64 on a RPi4 with the following configs:

(1)
```yaml
tts:
  - platform: picotts_remote
```
(2)
```yaml
tts:
  - platform: picotts_remote
    language: "en-US"
```

Thank you for bringing local tts to HA! 👍

**Comment by ebaschiera** [comment]
My component config is the following:
```
tts:
  - platform: picotts_remote
    language: "en-US"
```
Thanks!

**Comment by ebaschiera** [comment]
Related to this: https://github.com/home-assistant/core/issues/40244

**Comment by ebaschiera** [comment]
I confirm this issue is solved by https://github.com/home-assistant/core/issues/40244
PicoTTS works in Home Assistant 0.115.5.

Thanks!
